#!/usr/bin/env node
/**
 * postinstall.js — Make the binary executable on Unix systems.
 * Auto-generated by generate-platform-manifests.ts
 */
const { existsSync, chmodSync } = require("fs");
const { join } = require("path");

const pkg = require("./package.json");
const binaryPath = join(__dirname, pkg.main);

if (existsSync(binaryPath)) {
  try {
    chmodSync(binaryPath, 0o755);
  } catch {
    // Ignore chmod errors on Windows.
  }
}
