/**
 * generate-platform-manifests.ts — Create package.json and postinstall.js for
 * every platform-specific npm package.
 *
 * Usage:
 *   pnpm tsx scripts/generate-platform-manifests.ts
 */

import { pathToFileURL } from 'node:url';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, resolve } from 'node:path';
import config from '../publish.config';
import type { PublishConfig } from './types.ts';
import { PLATFORM_MAP } from './platforms.ts';

const ROOT = resolve(import.meta.dirname, '..');

function generatePostinstall(): string {
  return `#!/usr/bin/env node
/**
 * postinstall.js — Make the binary executable on Unix systems.
 * Auto-generated by generate-platform-manifests.ts
 */
const { existsSync, chmodSync } = require("fs");
const { join } = require("path");

const pkg = require("./package.json");
const binaryPath = join(__dirname, pkg.main);

if (existsSync(binaryPath)) {
  try {
    chmodSync(binaryPath, 0o755);
  } catch {
    // Ignore chmod errors on Windows.
  }
}
`;
}

export function generateManifests(root: string, cfg: PublishConfig, version?: string): number {
  const rootPkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
    license?: string;
  };
  const resolvedVersion = version ?? '0.0.0';
  const platformDir = join(root, 'platform-packages');
  let generated = 0;

  for (const binary of cfg.binaries) {
    for (const platform of cfg.platforms) {
      const mapping = PLATFORM_MAP[platform];
      if (!mapping) {
        console.error(`  ❌ Unknown platform: ${platform}`);
        continue;
      }

      const pkgName = `${cfg.scope}/${binary.scope}-${platform}`;
      const pkgDir = join(platformDir, `${binary.scope}-${platform}`);
      const binaryFile = `${binary.name}${mapping.ext}`;

      if (!existsSync(pkgDir)) {
        mkdirSync(pkgDir, { recursive: true });
      }

      const manifest = {
        name: pkgName,
        version: resolvedVersion,
        description: `${binary.name} binary for ${platform}`,
        os: [mapping.os],
        cpu: [mapping.cpu],
        main: binaryFile,
        files: [binaryFile, 'postinstall.js'],
        scripts: {
          postinstall: 'node postinstall.js',
        },
        license: rootPkg.license ?? 'MIT',
        repository: {
          type: 'git',
          url: cfg.repositoryUrl,
        },
        publishConfig: {
          access: 'public',
        },
      };

      writeFileSync(join(pkgDir, 'package.json'), JSON.stringify(manifest, null, 2) + '\n');
      writeFileSync(join(pkgDir, 'postinstall.js'), generatePostinstall());
      generated++;
    }
  }

  return generated;
}

function main(): void {
  const rootPkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
    version: string;
  };
  console.log(`📦 Generating platform manifests (version: ${rootPkg.version})`);
  const generated = generateManifests(ROOT, config, rootPkg.version);
  console.log(`\n📊 Generated ${generated} platform package(s)`);
}

const isMain = import.meta.url === pathToFileURL(resolve(process.argv[1] ?? '')).href;
if (isMain) {
  main();
}
